title: "نویز | NOYS"
description: "روایت‌های داستانی از کسب‌ و کارهای سایه، بیزینس‌های ممنوعه و اقتصاد زیرزمینی"
permalink: ':title/'
baseurl: ""
url: "https://noysdc.ir"
site-twitter: 

# Author Settings
author: یونس شجاعی
author-img: assets/css/fonts/img/avatar.png
about-author: مستندساز و روایت‌گر پرونده‌های سایه، بیزینس‌های ممنوعه و جریان‌های تاریک اقتصادی.
social-twitter: 
social-facebook: 
social-github: younesshojaei-crypto
social-linkedin: 
social-email: 

# Disqus
discus-identifier: 

# Tracker
analytics: 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]