title: NOYS
description: >
  روایت و مستند درباره آدم‌ها، ماجراها و سازوکارهایی که معمولاً پشت صحنه می‌مانند.

permalink: /:title/
baseurl: ""
url: "https://noysdc.ir"
site-twitter:

# Author Settings
author: NOYS
author-img:
about-author: روایت‌هایی درباره پرونده‌های واقعی، کسب‌وکارهای سایه، بازارهای سیاه و داستان‌هایی که ارزش دوباره شنیدن دارند.

social-twitter:
social-facebook:
social-github:
social-linkedin:
social-email:

# NOYS Social Media
social-youtube: "https://www.youtube.com/@NOYS-DC"
social-instagram: "https://instagram.com/noysdc"
social-telegram:

# Disqus
discus-identifier:

# Tracker
analytics:

# Build Settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude:
  - "node_modules"
  - "gulpfile.js"
  - "package.json"
  - "yarn.lock"